#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

unsetopt correct

. $HOME/bin/npm_completion.sh

alias pse="COLUMNS=1000 ps -e -o pid,user,command"
alias cd..=..
alias cd.=..
function gi() { curl -L -s https://www.gitignore.io/api/$@ ;}

